language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# gradlew가 denied되지 않게 권한 허용
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/spring-first-step-blog.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY
    bucket: tolgu-build # S3의 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private로 지정
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: tolgu-build
    key: spring-first-step-blog.zip # 빌드 파일을 압축햐서 전달
    build_type: zip # 압축 확장자
    application: spring-first-step-blog # 웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment_group: spring-first-step-blog-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-intil-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - rnjsehdgks01@naver.com